package com.tweetapp.model;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.Size;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@AllArgsConstructor
@Data
@DynamoDBTable(tableName = "Tweet")
public class Tweet {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String username;
	@DynamoDBAttribute
	private String tweet;
	@DynamoDBAttribute
	private boolean isLiked;
	@DynamoDBAttribute
	private int likeCount;
	@DynamoDBAttribute
	private Date date;
	@DynamoDBAttribute
	private int replyCount;
	@DynamoDBAttribute
	private List<RepliedTweet> repliedTweets;
	public Tweet(String username, String tweet, boolean isLiked, int likeCount, Date date, int replyCount,
			List<RepliedTweet> repliedTweets) {
		super();
		this.username = username;
		this.tweet = tweet;
		this.isLiked = isLiked;
		this.likeCount = likeCount;
		this.date = date;
		this.replyCount = replyCount;
		this.repliedTweets = repliedTweets;
	}
	
	

}
