version: "3"

services:
  zookeeper:
    image: zookeeper
    container_name: "tweet-zookeeper"
    ports:
      - 2181:2181
  
  kafka:
    image: bitnami/kafka
    container_name: "tweet-kafka"
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
 #     KAFKA_CREATE_TOPICS: "TweetTopic:1:1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      
  tweet-mongodb:
    image: mongo:latest
    container_name: "tweet-mongodb"
    ports:
      - 27017:27017
      
  tweet-app:
    image: tweet-app
    container_name: "tweet-app"
    ports:
      - 8080:8080
    links:
      - tweet-mongodb
   